server:
  port: 8084

#logging:
#  level:
#    root: debug
#    org.springframework: info

spring:
  application:
    name: mall-xxl-job

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl: 
  job: 
    admin: 
      addresses: http://192.168.100.101:8082/xxl-job-admin
      #addresses: http://localhost:8080/xxl-job-admin

    ### xxl-job executor address
    executor: 
      appname: xxl-job-executor-dongnao-mall
      ip: 
      port: 9999
      ### xxl-job log path
      logpath: /data/applogs/xxl-job/jobhandler
      ### xxl-job log retention days
      logretentiondays: -1

    ### xxl-job, access token
    accessToken: 
