# 服务端口
server:
  port: 5555
  
logging:
  level:
    com.dongnaoedu.mall.pay: debug

spring:
################# thymeleaf模板引擎 #################
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
    # 关闭缓存，即时刷新，上线生产环境需改成true
    cache: false
    mode: HTML
################# druid 数据源 #################
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性 url、user、password
      url: jdbc:mysql://mysql.dn.com:3306/dn_mall?characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      #配置 初始化大小、最小、最大
      initial-size: 2
      min-idle: 1
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters
      filters: stat,wall,config
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

################# jpa #################
  jpa:
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: true

################# mail starter #################
  mail:
    # JavaMailSender 邮件发送配置 以qq邮箱为例
    host: smtp.qq.com
    # 你的邮箱
    username: 
    # 你的邮箱授权码（不知道去百度）
    password: 
    # 服务器上请解封25端口或者使用465端口！
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

################# 日志 #################
  # 检查终端是否支持ANSI（是将采用彩色输出）
  output:
    ansi:
      enabled: detect
      
#################redis基础配置#################
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    host: redis.dn.com
    password: redis123456
    port: 6379
    # 连接超时时间 单位 ms（毫秒）
    timeout: 3000
#################redis线程池设置#################
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 0

################# 自定义配置 #################
# 服务器前部分域名 邮件中链接使用
domain: 
  url: http://127.0.0.1

token:
  admin:
    # 管理员链接有效时间(天)
    expire: 14
  fake:
    # 假管理员链接有效时间(小时)
    expire: 1

email:
  # 管理员接收者邮箱账号
  receiver: 
  # 发送者邮箱账号
  sender: 
  
fake:
  # 假管理员key前缀
  pre: FAKE-
  
# 防炸库缓存验证(分钟)
ip:
  expire: 2

# 二次加密
my:
  token: 

# 单个固定收款码共几张 填了多少去二维码文件夹配置多少张 不得少 例如配了5需在每个二维码文件夹配置名为1至5.png的收款码！
qrnum: 5
