server:
  port: 8083

spring:
  activemq:
    broker-url: tcp://192.168.100.100:61616
    user: admin
    password: admin

  redis:
    database: 0
    host: 192.168.100.101
    password: redis123456
    port: 6379
    timeout: 0
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 1
#    cluster:
#      nodes:
#      - 
#    sentinel:
#      master: 
#      nodes:
#      - 
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性 url、user、password
      url: jdbc:mysql://mysql.dn.com:3306/dn_mall?characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      #配置 初始化大小、最小、最大
      initial-size: 2
      min-idle: 1
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filters
      filters: stat,wall,config
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      
      #配置 Druid 监控信息显示页面
      stat-view-servlet:
        #允许清空统计数据
        enabled: false
        #allow: 127.0.0.1
        #deny: 192.168.1.73
        login-username: admin
        login-password: admin
        reset-enable: false
        url-pattern: /druid/*
      #WebStatFilter用于采集web-jdbc关联监控的数据
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        url-pattern: /*
        
mybatis:
    type-aliases-package: com.dongnaoedu.mall.manager.pojo
    mapper-locations: classpath:com/dongnaoedu/mall/manager/mapper/*.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#用户登录过期时间30分钟
SESSION_EXPIRE: 1800
#用户购物车
CART_PRE: CART

#支付验证邮箱配置 以QQ邮箱为例
EMAIL_HOST: smtp.qq.com
EMAIL_USERNAME: 你的接收邮箱账号
EMAIL_PASSWORD: 密码(非邮箱账号密码)
EMAIL_SENDER: 你的发送邮箱账号

#支付验证token过期时间 二周
PAY_EXPIRE: 1209600

#服务器或域名前端链接
SERVER_URL: http://localhost:8888

