server:
  port: 7777
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 3145728
  # 启用压缩
  compression:
    enabled: true
    mime-types:
    - application/json
    - application/xml
    - text/html
    - text/xml
    - text/plain
    - application/javascript
    
#logging:
#  level:
#    root: debug
#    org.springframework: info
    
spring:
  application:
    name: mall-front-web
  # Spring boot http编码配置(CharacterEncodingFilter)
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
      
  servlet:
    multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 5MB
      # 上传多个文件最大值,50Mb,默认10Mb
      max-request-size: 10MB
      
#################redis基础配置#################
  redis:
    database: 0
    host: 192.168.100.101
    password: redis123456
    port: 6379
    # 连接超时时间 单位 ms（毫秒）
    timeout: 3000
#################redis线程池设置#################
    jedis:
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 10
        # 连接池中的最小空闲连接，默认值也是0。
        min-idle: 0
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
        max-active: 20
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 1000
#    cluster:
#      nodes:
#      - 
#    sentinel:
#      master: 
#      nodes:
#      - 
#################自定义属性#################
# 启用全局限流
mall.rateLimit.enable: true
# 每1秒内
mall.rateLimit.timeout: 1000
# 限制10个请求
mall.rateLimit.limit: 20

